### ISSUE TITLE
Make file

### ISSUE THREAD

**Issue by anshumitts** [rupea/LabelFilters#1]
Can you provide a bash script to download and make all the dependencies along with LabelFilters? I tried from my side but there seem to be version issues with boost.

Thank you in advance.

**Comment by rupea** [comment]
Can you let me know what issues are you encountering with boost? I have compiled the code with the latest version of boost and things look OK.

**Comment by anshumitts** [comment]
Thank you for your reply. I was struggling to setup on a system for which I have no root access. Found the way around though.
